애니매이션 변경 및 초대장 로딩 대기
mash-up-kr/Nawa-Invitation-Web pull request #78
Opened 2020-08-31 10:11 UTC by joi0104

### # 변경사항
초대장 데이터가 불러오는 동안 로딩 애니매이션 띄우기

### # 변경 세부사항
- `PopAnimation` -> `LoddingAnimation` 으로 이름변경
- `useDuration` 삭제

### # 테스트
- [ ] 테스트 케이스 작성(SnapShot테스트 제외).
- [x] 로컬 테스트 (Staging server) 완료.

### # 이슈
- close #66

2020-08-31 10:19 UTC, joi0104 commented on src/containers/InvitationContainer.tsx
> +        await dispatch(invitationAction.getInvitation({ invitationId })).promise.then(() => setIsLodding(false))
`isLodding`을 사용해서 로딩과 초대장 페이지의 전환이 일어나도록 함

2020-08-31 10:19 UTC, joi0104 commented on src/components/LoddingAnimation/LoddingAnimation.tsx
> +import styled from './LoddingAnimation.module.scss'
`PopAnimation`보다는 `LoddingAnimation`이 더 적절한 것 같아 네이밍 변경

2020-08-31 10:19 UTC, joi0104 commented on src/components/LoddingAnimation/LoddingAnimation.tsx
> -import useDuration from 'hooks/useDuration'
안녕.. 나의 첫 custom hook...

2020-08-31 14:21 UTC, danivelop requested changes

2020-08-31 14:21 UTC, danivelop commented on src/containers/InvitationContainer.tsx
> +  const [isLodding, setIsLodding] = useState(true)
```suggestion
  const [isLodding, setIsLodding] = useState<boolean>(true)
```

2020-08-31 14:21 UTC, danivelop commented on src/containers/InvitationContainer.tsx
>        }
```suggestion
      } finally {
        setIsLodding(false)
      }
```

2020-08-31 14:21 UTC, danivelop commented on src/containers/InvitationContainer.tsx
> +  }, [invitationId, history, dispatch, setIsLodding])
여기서는 의존성에 `setIsLodding`은 없어도 될거같아요
지웠을때 lint에러만 안난다면 제거해주셔도 될 것 같습니다!

2020-08-31 14:21 UTC, danivelop commented on src/containers/InvitationContainer.tsx
> +        await dispatch(invitationAction.getInvitation({ invitationId })).promise.then(() => setIsLodding(false))
```suggestion
        await dispatch(invitationAction.getInvitation({ invitationId })).promise
        setIsLodding(false)
```
여기서 비동기적 로직을 쓴다면 이미 es2017문법이 쓰였기 때문에 async await문법을 쓰는게 좋을것 같아요
추가적으로 try구문 안에서만 `isLodding`값을 업데이트 시켜준다면 서버에러 등의 이유로 에러가 발생해서 catch구문으로 가게 된다면 `isLodding`이 업데이트 되지 않아 계속 로딩상태의 화면을 보게 될수 있어 finally문 안에서 업데이트 시키는게 좋을것 같아요

2020-08-31 14:21 UTC, danivelop commented on src/containers/InvitationContainer.tsx
> +  return isLodding ? <LoddingAnimation /> : <Invitation invitation={invitation} />
이렇게 되면 혹시 로딩 애니메이션이 초대장데이터를 서버로부터 받아오기전까지만 짧은시간만 보여질것 같은데 기획상 의도는 로딩애니메이션을 최소 2~3초?정도는 보여주는걸로 기억해요!

2020-09-01 16:07 UTC, joi0104 reviewed
re self-review!

2020-09-01 16:07 UTC, joi0104 commented on src/containers/InvitationContainer.tsx
>  /* External dependencies */
`3초 동안에도 로딩되지 않는 기기는 고려하지 않는것이 좋을듯` 라고 말씀하셨는데 아무래도 `네트워크가 너무 느려서 3초 이상이 걸리는 경우`가 꽤 있을 것 같았고, 또 `이미지 보여주기 기능 등등`이 추가되면 데이터가 무거워질수도 있겠다고 생각하였습니다. 그래서 3초 이후에도 로딩 애니매이션을 보여주는 게 맞다고 판단하여 이대로 진행하였습니다!

2020-09-01 16:07 UTC, joi0104 commented on src/containers/InvitationContainer.tsx
> +  const [isFetching, setIsFetching] = useState<boolean>(true)
두가지 조건 충족여부를 확인하기 위해 `isLoading` `isFetching`을 추가하였습니다.

2020-09-01 16:07 UTC, joi0104 commented on src/containers/InvitationContainer.tsx
>    }, [invitationId, history, dispatch])
useEffect 가 지저분해지는 것 같아 `fetchInvitation` 함수를 생성하였고 `useCallback` 을 통해서 의존성을 관리하였습니다.

2020-09-01 17:13 UTC, danivelop requested changes

2020-09-01 17:13 UTC, danivelop commented on src/containers/InvitationContainer.tsx
> +  const [isFetching, setIsFetching] = useState<boolean>(true)
초대장을 fetching중일때의 플래그 값은 이미 `InvitationReducer`에 정의되어있는 값이라서 이값을 얻어오는 selector를 작성하고 작성된 selector를 통해 사용하는게 나을것 같아요!

2020-09-01 17:13 UTC, danivelop commented on src/containers/InvitationContainer.tsx
> +  const LOADING_TIME = 3000
이 값은 상수이면서 컴포넌트에서 사용만 되기 때문에 아예 컴포넌트 바깥으로 빼주는게 성능면에서 좋을것 같아요
만약 컴포넌트 내에서 값이 변하지만 변경될때마다 컴포넌트 렌더링까지는 필요없는 값이 있다면 (클래스의 멤버변수와 같은개념) 그때는 리액트 커뮤니티에서는 useRef훅을 통해 변수를 선언하는것을 권장하고 있습니다

2020-09-01 17:13 UTC, danivelop commented on src/containers/InvitationContainer.tsx
> +    }
위의 초대장fetching값을 리듀서에서 얻어온다면 이부분 삭제되어도 괜찮을것 같습니다!

2020-09-02 11:30 UTC, joi0104 reviewed
리팩토링 진행하겠습니다!

2020-09-02 11:30 UTC, joi0104 commented on src/containers/InvitationContainer.tsx
> +  const [isFetching, setIsFetching] = useState<boolean>(true)
오오 리듀서에 정의되어있는걸 미쳐 생각 못했네요 ㅎㅎㅎ fetching 상태 가져오는 방식으로 리팩토링 진행하겠습니다!

2020-09-02 11:30 UTC, joi0104 commented on src/containers/InvitationContainer.tsx
> +  const LOADING_TIME = 3000
아아 그렇네요! 이 값은 컴포넌트 내에서 변하지 않을 것 같으니 컴포넌트 밖으로 뺴주겠습니다!

2020-09-02 11:30 UTC, joi0104 commented on src/containers/InvitationContainer.tsx
> +    }
넵!

2020-09-06 11:46 UTC, joi0104 commented on src/containers/InvitationContainer.tsx
> +  const isFetching = useSelector(invitationSelector.getInvitationFetching)
selector에서 fetching 값 받아오기

2020-09-06 11:46 UTC, joi0104 commented on src/redux/selectors/invitationSelector.ts
> +export const getInvitationFetching = (state: rootState) => state.invitation.getInvitationFetching
getInvitationFetching 정의

2020-09-06 11:46 UTC, joi0104 commented on src/containers/InvitationContainer.tsx
> +const LOADING_TIME = 3000
상수 바깥으로 뺴주기

2020-09-06 12:32 UTC, danivelop requested changes

2020-09-06 12:32 UTC, danivelop commented on src/containers/InvitationContainer.tsx
> +  const isFetching = useSelector(invitationSelector.getInvitationFetching)
마이너하지만 아래도 useSelector로직이 쓰였으니(L24) 같은로직끼리는 코드를 모아서 써주는게 좋을것 같습니다!

2020-09-06 12:32 UTC, danivelop commented on src/containers/InvitationContainer.tsx
> +      await dispatch(invitationAction.getInvitation({ invitationId }))
```suggestion
      await dispatch(invitationAction.getInvitation({ invitationId })).promise
```
제가 지난 리뷰때 놓쳤었나봐요ㅠㅠ 뒤에 promise가 빠져있으면 해당 액션은 프로미스를 호출하는게 아니라 비동기 로직이 정상적으로 작동하지 않습니다 `.promise`만 추가해주면 될것 같습니다

2020-09-06 15:14 UTC, joi0104 commented on src/containers/InvitationContainer.tsx
> +      await dispatch(invitationAction.getInvitation({ invitationId }))
반영하였습니다!

2020-09-06 15:14 UTC, joi0104 commented on src/containers/InvitationContainer.tsx
> +  const isFetching = useSelector(invitationSelector.getInvitationFetching)
반영하였습니다!

2020-09-06 16:34 UTC, danivelop approved these changes

2020-09-07 07:06 UTC, merged