helmet 개선 및 og helmet 추가
mash-up-kr/Nawa-Invitation-Web pull request #86
Opened 2020-09-07 12:03 UTC by joi0104

### # 변경사항
helmet 개선 및 og helmet 추가

### # 변경 세부사항
- `components/Helmet`에 Helmet 컴포넌트 추가 및 내용 개선. 
-  `og helmet` 추가.
- `title` 이나 `description` 은 회의를 통해서 개선할 예정.
- `og helmet` 에서도 동적으로 `title` `description` 을 넣을 수 있도록 개선할 예정.

### # 테스트
- [ ] 테스트 케이스 작성(SnapShot테스트 제외).
- [x] 로컬 테스트 (Staging server) 완료.

### # 이슈
- close #60

2020-09-07 12:10 UTC, joi0104 commented on public/index.html
> +    <meta property="og:image" content="https://nawa-invitation.s3.ap-northeast-2.amazonaws.com/og-images/envelope.png" />
최대한 떠오르는 문구로 작성해봤어요! 더 좋은 문구가 있다면 말씀해주세요!

2020-09-07 12:10 UTC, joi0104 commented on src/App.tsx
> +      <Helmet title="나와 초대장" description="나와 초대장입니다." />
최상위 `meta tag` 즉, `index.html`에 정의된 `meta tag`와 동일하게 작성하였습니다. 아 또한, 에러 페이지와 같이 `나와 - ...` 형식의 `title`이 적용되지 않는 곳도 존재하여 `titleTemplate`는 삭제하였습니다.

2020-09-07 12:10 UTC, joi0104 commented on src/components/Error/Error.tsx
> +      <Helmet title={`${errorStatusCode} ${errorTitle}`} description={errorContent} />
이부분은 그냥 원래와 동일하게 title과 description을 작성하였습니다!

2020-09-07 12:10 UTC, joi0104 commented on src/components/Invitation/Invitation.tsx
>              </div>
충돌을 처리하면서 div하나가 모자르길래 여기에 추가하였는데, 테스트 상 문제는 없었지만 확인 부탁드립니다!

2020-09-07 15:10 UTC, danivelop requested changes

2020-09-07 15:10 UTC, danivelop commented on src/components/Preview/Preview.tsx
> +      <Helmet title="초대장 미리보기" description="초대장 미리보기 입니다" />
Preview는 안드로이드에서만 사용되는 템플릿으로 일반사용자에게 공개되는 페이지가 아니어서 여기에는 helmet를 빼도 될것같아요

2020-09-07 15:10 UTC, danivelop commented on src/components/Invitation/Invitation.tsx
> +                    <div className={cx('info-content')}>{getDate(invitation.time)}</div>
잉??? 이부분이 중복되네요ㅋㅋㅋㅋ 아마 복붙하면서 뭔가 꼬인것같습니다

2020-09-07 15:10 UTC, danivelop commented on src/components/Helmet/Helmet.tsx
> +      <meta name="description" content={description} />
`Helmet`컴포넌트는 비동기적으로 태그를 주입하는데 이곳에 descrption은 넣어도 효과가 없는 코드가 될수 있을것 같습니다. 서버사이드렌더링이 아닐때 helmet를 사용해 동적으로 description을 넣어주는것에 대한 효과를 확인함 부탁드리고 혹시 효과가 없다면 제거해도 괜찮을듯 합니다

2020-09-07 15:14 UTC, danivelop commented on public/index.html
> +    <meta name="description" content="나만의 특별한 초대장 파트너" />
요문구 참 맘에드네요

2020-09-07 15:14 UTC, danivelop commented on public/index.html
> +    <meta property="og:image" content="https://nawa-invitation.s3.ap-northeast-2.amazonaws.com/og-images/envelope.png" />
문제없어 보입니다!

2020-09-07 16:52 UTC, joi0104 commented on src/components/Preview/Preview.tsx
> +      <Helmet title="초대장 미리보기" description="초대장 미리보기 입니다" />
넵 제거하였습니다!

2020-09-07 16:53 UTC, joi0104 commented on src/components/Invitation/Invitation.tsx
> +                    <div className={cx('info-content')}>{getDate(invitation.time)}</div>
아 ㅋㅋㅋ 그래서! div하나가 부족했군요! 충돌 해결하다가 중복해버렸네요 ㅎㅎ 수정하였습니다!

2020-09-07 16:54 UTC, joi0104 commented on src/components/Helmet/Helmet.tsx
> +      <meta name="description" content={description} />
아아 그렇네요 그럼 title만 두도록 수정하겠습니다! (혹시나 해서 테스트 해봤는데 역시나 안되더라구요..)

2020-09-08 10:24 UTC, danivelop approved these changes

2020-09-08 11:18 UTC, merged